FROM ubuntu                                                                                                                              
MAINTAINER babonet13 <admin@hubject.net>                                                                                                 
RUN apt-get update
RUN apt-get install -y nano
ENTRYPOINT /bin/bash        
