FROM ubuntu                                                                                                                                                                                                                           
RUN apt-get update
RUN apt-get install -y nano
ENTRYPOINT /bin/bash        
